### ISSUE TITLE
Separate contracts into designated folders

### ISSUE THREAD

**Issue by capsulecorplab** [Giveth/planning-app#114]
file structure should look like:
```
planning-app/
└─ apps/
   ├─ address-book/
   ├─ payout-engine/
   └─ range-voting
```

**Comment by stellarmagnet** [comment]
not sure if there should be a parent "planning app" folder since one of the apps is the planning app

file structure should look like:
```
└─ apps/
   ├─ address-book
   ├─ allocations
   └─ range-voting
   └─ planning
```

**Comment by capsulecorplab** [comment]
@stellarmagnet the root directory is called `planning-app` by default because that's the name of the repo.

**Comment by Quazia** [comment]
I think we're on the same page with this. I'm all for calling the folder that holds the "PayoutEngine" contract allocations, I think for clarity sake we should probably rename the contract to Allocations?

**Comment by capsulecorplab** [comment]
I concur. 'Allocations', semantically speaking, makes more sense.
