### ISSUE TITLE
Allocations App - Frontend

### ISSUE THREAD

**Issue by stellarmagnet** [Giveth/planning-app#119]
aka "Payout engine"

Specs: https://docs.google.com/document/d/1P26rygmsa6TiHwRW2DEsAB7ckgL8bJlFa050jWqq62Q/edit#heading=h.7g2kmi1l0bzp

Designs: https://invis.io/7HMJ9VZB8NY

Note: Monthly Allocation feature is a "nice to have" and not top priority.

**Comment by deamme** [comment]
Pretty much done but there are some minor things e.g. missing right svg's etc. I've asked my questions on Invision
