### ISSUE TITLE
Projects App - Backend

### ISSUE THREAD

**Issue by stellarmagnet** [Giveth/planning-app#121]
The scope of work for this ticket for the Projects app requires coding the solidity (including ACL permissions) and interfacing with the StandardBounties smart contract.

- [Specs](https://docs.google.com/document/d/1Ub332Ad8aRXmJJ7klWoQ2ogHLdYy8fzE5RrKkUnKd6A/edit#heading=h.4i7ojhp)
- [Design](https://invis.io/XHM4USVDAZR): Scroll to find the 'Projects' section

**Comment by topocount** [comment]
The Issues are passing all tests as of a few weeks ago. 
I've looked through the Standard Bounties contract and documentation and have walked through the call sequences we would employ to utilize their interfaces. However, I'm not exactly sure how we should implement what they have to store bounties onchain. It seems like our options are:
* making calls to the currently deployed instance of the standard bounties contract to store bounties there
* copy the standard bounty functionality into our Projects contract and utilize a subset of it
* implement an entirely different workflow where the bounties are not stored in some form of a standard bounties contract, but are instead kept in the project fund and are issued through an entirely different workflow.

I'm working under the assumption of option 2 at the moment.
We should be able to write some frontend scripts that will auto-fund bounties given the bounty size labels. I'm just not sure what our architecture should be at the moment.
