### ISSUE TITLE
Range Wizard - Backend only

### ISSUE THREAD

**Issue by stellarmagnet** [Giveth/planning-app#124]
Just going to focus on the smart contracts

Specs: https://docs.google.com/document/d/1P26rygmsa6TiHwRW2DEsAB7ckgL8bJlFa050jWqq62Q/edit#heading=h.4q3jdkghenav

But for future reference, here are the designs: 
https://invis.io/MXMJABEGFKR

**Comment by Quazia** [comment]
We're just going to handle this with a kit for the time being so this task requires writitng the ``Kit.sol`` file.
