### ISSUE TITLE
UI component: (x) remove icon

### ISSUE THREAD

**Issue by stellarmagnet** [Giveth/planning-app#14]
We need an icon that looks similar to add:
https://ui.aragon.one/icons/

It should be a grey circle with an x. Used for removing options in range voting applications, during the "create" flow. But this will likely be used across many other aspects of Aragon apps.

- #717171
- 22px by 22px
- svg

![image](https://user-images.githubusercontent.com/2584493/38222801-00fa500c-369c-11e8-8db9-dfc270d360a4.png)

Can use this for now: https://www.dropbox.com/s/g8g8w75vcbehr9l/remove.svg?dl=0

**Comment by ottodevs** [comment]
I think is the same as the "Add" icon but just applying a 45 deg rotation, I already did this while coding Range Voting side panel.

`transform: rotate(45deg);`

And the result:
<img width="61" alt="image" src="https://user-images.githubusercontent.com/5030059/41962767-2b99f7a2-79f6-11e8-9408-d231b8284cb0.png">

**Comment by ottodevs** [comment]
I think this issue is trivial and more than finished, so for cleaning purposes I close the issue if you don't mind.
