### ISSUE TITLE
Full tests working for Allocations contract

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#145]
The general flow is being tested but a full set of tests need to be composed the same way that they are in the RangeVoting contract. As long as there’s full coverage this is good, but the coverage should be such that we can tell exactly what’s wrong based on the test that’s failing. Remember that all we’ll get is a revert message if something goes wrong with a contract so the context of _which test_ should be enough to tell us exactly where in the code we’re experiencing an error.

**Comment by topocount** [comment]
Will start working on this when #146 is done.

**Comment by topocount** [comment]
All key tests are outlined, but more can be added as each context gets filled out. executePayout reverting at the moment. See here: b6c3c0fc26755203907de931b26e5083c1f4754a for more details.

**Comment by topocount** [comment]
All tests are passing. Need to do some cleanup, then will create a PR. @Quazia what branch should I merge to for the PR? Here's the latest commit: 10165a010c45021676f676c3f6eed9d46e346f01
