### ISSUE TITLE
Full tests working for RangeVoting contract

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#146]
For the most part this just means uncommencting the tests that are present currently and making sure that they all pass. Some of them may need to be modified as the contract has changed around a little. For all of the tests that rely on the vote execution function that function needs to be adapted to take into account the end of the script. Right not the execution function assumes that all of the script parameters will be re-assembled in the RangeVoting contact which is not the case. Anything after the _second_ parameter will need to be copied onto the end of the script using assembly.

**Comment by topocount** [comment]
@Quazia: Sean and I started looking through the `RangeVoting App normal token supply execution scripts can execute actions` test and I started parsing the assembly, but we didn't make any changes. If you want to focus on the assembly codes in executeVote, We can work on the remaining assertion errors. Up to you.

**Comment by Quazia** [comment]
Yeah that sounds good. I'll check in when the _executeVote function works.
