### ISSUE TITLE
Babel-related conflicts

### ISSUE THREAD

**Issue by stellarmagnet** [Giveth/planning-app#159]
We've been troubleshooting some Babel-related conflicts this past week. As a sanity check, I cloned and ran npm start with the aragon/aragon-react-boilerplate app and got the following error, which makes me think a dependency might have changed in the Aragon stack (unless I'm just missing something silly):

```
 app-name@1.0.0 build:app /home/kevin/Projects/aragon-react-boilerplate
 parcel build app/index.html -d dist/ --public-url '.' --no-cache

  /home/kevin/Projects/aragon-react-boilerplate/app/main.js:50:11: Unexpected token (50:11
  48 |   }
  49 |   render() {
 50 |     return <App {...this.state} />
     |           ^
  51 |   }
  52 | }
  53 | ReactDOM.render(
```

**Comment by Quazia** [comment]
The error you're getting is unrelated as far as I can tell, but it is an issue in the aragon stack.

aragon/aragon-cli#217
