### ISSUE TITLE
We should use the theme colors and not hard code CSS colors

### ISSUE THREAD

**Issue by stellarmagnet** [Giveth/planning-app#177]
see here: https://github.com/Giveth/planning-app/blob/6d4f098d0b56dd5f07dda0c2b13c483332428058/apps/allocations/app/components/AccountCard.js#L72

theme colors: https://ui.aragon.org/theme/

**Comment by ottodevs** [comment]
Fixed in [commit#a998de4](https://github.com/Giveth/planning-app/commit/a998de4008eb64aa3f33bed69e0b965ef4da5b5e).

We should close this 🥇

**Comment by stellarmagnet** [comment]
i think we still need a ticket open for the rest of the app, right? have we gotten rid of all font colors that are using hard coded hexes?

**Comment by ottodevs** [comment]
Done 👍
