### ISSUE TITLE
Implement canExecute

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#23]
`canExecute` is used to check that the participation has been met and the vote has reached its end before the execute function is called.
    * param `_voteId`: The ID of the Vote which would be executed.
    * return `True` if the vote is eligible for execution.

`_minParticipationPct` is percentage of voters that must participate in a vote for it to succeed (expressed as a 10^18 percentage, (eg 10^16 = 1%, 10^18 = 100%)

This issue should be accompanied by tests.

**Comment by aenhsaihan** [comment]
@Quazia @capsulecorplab Just saw the chat on Riot, should we merge in your fix to flesh out testing for this issue?

**Comment by capsulecorplab** [comment]
Update: this issue is about 80% done. The current tests need to be rewritten to account for vote timeout, so  `if (_isVoteOpen(vote)) return false;` is commented out at the moment. Other than that, the tests for the min candidate support and min quorum are passing.
