### ISSUE TITLE
implement getVote and getVoterState

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#24]
Both functions should return data.

`getVote` simply splits all of the data elements out of a vote struct and returns the individual values.
    * param: _voteId The ID of the Vote struct in the `votes` array

`getVoterState` allows a user to get the vote weights for a given voter.
    * param: _voteId The ID of the Vote struct in the `votes` array.
    * param: _voter The voter whose weights will be returned

This issue should be accompanied by tests.

**Comment by capsulecorplab** [comment]
Just so I'm reading correctly, would `getVote` return an array of size 11, of which 2 elements are mappings?

**Comment by Quazia** [comment]
Can't return mappings, there's a getter for the CandidateStates and all of the keys will be returned in the getVote.

**Comment by capsulecorplab** [comment]
Okay, that makes more sense. So the last 2 return elements will just be arrays containing keys of type `bytes32[]` and `address[]`

**Comment by Quazia** [comment]
No, the ``candidateKeys`` array. The bytes32 key for the ``candidates`` mapping is just the keccak256 of the ``candidateKeys`` string. Having an array of keys (in some form) is like the best "it'll do the job" solution to iterating through mappings in solidity. Still in general not best practice since you can run into some gas issues with this approach but it's IMO the best approach here. You don't actually need to return anything for the last two mappings for getVote. getVote should [return 9 separate elements](http://solidity.readthedocs.io/en/v0.4.21/control-structures.html#multi-return); solidity is strongly typed so it'd be impossible to put all 9 things in the same array.

**Comment by capsulecorplab** [comment]
@Quazia thanks for the clarification on multi-return (that was a derp moment), though I feel like I'm still missing something. Is the last getVote return element, `candidateKeys`, to be an array of strings? It doesn't look like Solidity supports this http://solidity.readthedocs.io/en/v0.3.1/frequently-asked-questions.html#is-it-possible-to-return-an-array-of-strings-string-from-a-solidity-function

Here's what I have so far:

```
function getVote(uint256 _voteId) public view returns (address, uint64, uint256, uint256, uint256, string, bytes, bool /*, string[]*/) {
        Vote memory _vote = votes[_voteId];
        address _creator = _vote.creator;
        uint64 _startDate = _vote.startDate;
        uint256 _snapshotBlock = _vote.snapshotBlock;
        uint256 _candidateSupportPct = _vote.candidateSupportPct;
        uint256 _totalVoters = _vote.totalVoters;
        string _metadata = _vote.metadata;
        bytes _executionScript = _vote.executionScript;
        bool _executed = _vote.executed;
        /*string[] _candidateKeys = vote.candidateKeys;*/
        return (_creator, _startDate, _snapshotBlock, _candidateSupportPct, _totalVoters, _metadata, _executionScript, _executed /*, _candidateKeys*/);
}
```

I'm also a bit unsure as to what getVoterState() is supposed to return - or is this to pull from a struct that hasn't been written yet?
