### ISSUE TITLE
Range voting wizard - front-end true up

### ISSUE THREAD

**Issue by stellarmagnet** [Giveth/planning-app#27]
The front-end of the range voting wizard needs to be trued up to match the designs.

[Review specs](https://docs.google.com/document/d/1tZ-PI38cBRh2-S1WVbe3h3OgFRfkwLjErgELfKgaqec/edit#heading=h.tg1pdihqii7a)

**Comment by rkzel** [comment]
Initial commit done. Remaining: adding candidates screen, review, signing. And details in styling needs some improvement.
