### ISSUE TITLE
Tools tab - Front-end

### ISSUE THREAD

**Issue by stellarmagnet** [Giveth/planning-app#56]
The tools tab is part of the planning app, and where the range voting objects live.

[Review specs](https://docs.google.com/document/d/1tZ-PI38cBRh2-S1WVbe3h3OgFRfkwLjErgELfKgaqec/edit#heading=h.c6f8svi5y71e)

**Comment by ottodevs** [comment]
The tools tab was already finished and reviewed by @deamme and @rkzel , for cleaning purposes I close this old issue.
