### ISSUE TITLE
Github Integration Middleware

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#57]
For initial [github integration](https://docs.google.com/document/d/192hg6lUoePoWh_zR2uCyIHcw7TYH4gEc7CoUMZ1lkl8/edit#heading=h.b64uc442y3f) we need a way to [handle Oauth](https://developer.github.com/apps/building-oauth-apps/authorization-options-for-oauth-apps/#web-application-flow) and [interact with issues](https://developer.github.com/v3/issues/). We need at a minimum the ability to list issues, and edit issues.

**Comment by stellarmagnet** [comment]
Closing this epic - I rolled up the issues here: https://github.com/Giveth/planning-app/issues/64
