### ISSUE TITLE
Setup Virtual AWS testnet

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#63]
Play around with AWS Ethereum Blockchain.

**Comment by rkzel** [comment]
Played. Can't easily set it up - creation of BC machines results in various errors, few attempts were unsuccessful. Rinkeby, on the other hand, seems quite usable for testing - creation of new DAOs using local Aragon interface, for example, works well. In case (unlikely) we need a private network it might be easier to create it manually on all the VMs we have at our disposal.
