### ISSUE TITLE
As a user finishing the project addition flow will populate the app

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#75]
On clicking the Finish button the projects selected will automatically be added to the overview tab, and the corresponding issues will be populated into the Issues tab.

**Comment by rkzel** [comment]
Half-way through: Finish button makes the selected projects appear in the overview tab.
TODO:
1. Styling and information in cards representing repos,
2. Issues are not done yet.

**Comment by rkzel** [comment]
Styling is better and information is present (required switching to graphql instead of the usual API). Issues are being done now.

**Comment by rkzel** [comment]
Issues tab is now being populated. Todo: prettifying results, adding labels, links, etc.

**Comment by rkzel** [comment]
This is pretty much done. GitHub provides enough data to populate (and manipulate) repos, issues, labels and milestones. Bounties are out of scope for this ticket, for now.
