### ISSUE TITLE
UI: selecting Tab needs smooth transition of highlight

### ISSUE THREAD

**Issue by rkzel** [Giveth/planning-app#85]
On vertical App menu (in Aragon wrapper) selecting another App makes vertical teal bar (left side of the selected App MenuItem) appear with quick transition. The same needs to happen on horizontal Planning App main menu (Issues, Dashboard, etc). Currently the highlight is realised with border-bottom - it looks ok, but no smooth transition.

**Comment by ottodevs** [comment]
Since we are not using an horizontal bar anymore I think **this can be closed**, anyway I did a performant smooth animated horizontal bar, I think the work is better than previous design, if anywhere in the future we need it for some reason.
