### ISSUE TITLE
Design UML for range voting smart contracts

### ISSUE THREAD

**Issue by Quazia** [Giveth/planning-app#9]
We need a basic UML diagram for the range voting application.

This should be fairly straightforward. Since it's a single contract we just need one class diagram. As we build more of the class diagrams we will begin to aggregate them into a single UML diagram. We can also include the Aragon elements we're interacting with in that chart but this isn't a priority.

We can use https://www.draw.io/ unless somebody has something else they prefer. I've used https://sketchboard.io/ as well but personally prefer draw.io but will go with whatever people prefer. Open to other suggestions as well.

https://www.draw.io/?state=%7B%22ids%22:%5B%2218AeUPYwlAFtiO43ZmjwJTluWyS4aqnvY%22%5D,%22action%22:%22open%22,%22userId%22:%22115872595772615656010%22%7D#G18AeUPYwlAFtiO43ZmjwJTluWyS4aqnvY

**Comment by capsulecorplab** [comment]
I can help with this.

**Comment by Quazia** [comment]
Ok, at this point most of it's done but if you want to give it a look that would be extremely helpful. Just making sure everything is consistent and the design seems logical would be invaluable. Once you give it a look over we can probably close this issue.

**Comment by Quazia** [comment]
https://docs.google.com/document/d/1gKUdr_FAOG0oMyXlc5erm2kEOWSUmnOC4MdlJF9vJoE/edit Here are my design process and assumptions and here's the draw.io file with the finished diagrams for the RangeVoting.
https://drive.google.com/open?id=18AeUPYwlAFtiO43ZmjwJTluWyS4aqnvY
